### ISSUE TITLE
Github auth not working on Chrome for iOS

### ISSUE THREAD

**Issue by leobalter** [Vestorly/torii#141]
I have an internal app using the torii authentication and it's working almost on every device, but currently we found it's now working on Chrome of iOS.

It opens the popup at github, I authenticate myself there, but when I return to my app nothing happens.

I'm filing this as I didn't got enough time to debug it to see what is exactly missing, maybe someone already knows and we can fix it directly in torii.

**Comment by anilmaurya** [comment]
@leobalter I also faced similar issue, I submitted a pull request https://github.com/Vestorly/torii/pull/187 to fix this. Can you check and confirm if your Issue is also resolved by this pull request.

**Comment by rduque1** [comment]
Hallo i have the same issue on Chrome of iOS and i am using 0.5.1 version of torii. So normally the pull request #187  is in it. So it does not fix the issue?

I get "Popup could not open or was closed". But the popup opens and I get the login of the oauth provider. So my guess is that the origin window does not get the response from the popup.

**Comment by anilmaurya** [comment]
@rduque1 I am using iOS chrome Version 44.0, torii `https://github.com/anilmaurya/torii` and its working for me , may be newer version of torii introduced this bug again.

**Comment by rduque1** [comment]
@anilmaurya thanks with your fork it's working.

So yes the bug is reintroduced in the newer version of torii. Actually it is for all oauth logins that the it fails, because the response of the popup window is never passed to the parent window.
