### ISSUE TITLE
Facebook-Oauth2 provider does not work in Chrome on iOS 

### ISSUE THREAD

**Issue by rickpern** [Vestorly/torii#205]
Even the demo at http://vestorly.github.io/torii/demo.html does not seem to be functional. 

Go to the demo url and click "Facebook OAUTH2", then log in to Facebook. When the "popup" closes nothing happens...no auth data is loaded in the view because there was an error.

If you want to see the error you can simply add this method as an action to one of your routes:

```
actions: {
  signInViaFacebook: function () {
    this.get('torii').open('facebook-oauth2').then(function(){
      alert('logged in')
    }, function(error){
      alert('error: ' + error);
    });
  }
}
```
You won't ever get alerted 'logged in' but you will see the error, "Popup could not open or was closed."

I'm currently using the latest release of torii (0.5.1) and the latest Chrome on iOS (44.0.2403.65).

Thanks!!!

**Comment by mixonic** [comment]
The version of Torii on that demo page is very out of date, and not representative of the current codebase.

**Comment by rickpern** [comment]
@mixonic i'm running master locally and can't get it to work.  I have a few updates though:

1. I found that when you do `window.open(URL, NAME, OPTS)` and specify anything other than `_blank` for the `NAME` option, there is NO return value, so the promise is immediately rejected.

2. The localStorage events don't seem to work on iOS Chrome, basically `Ember.$(window).on('storage.torii', ...)` never gets fired.

That's all i got so far.

**Comment by mixonic** [comment]
@rickpern can you confirm what this guy says?

* https://productforums.google.com/forum/#!topic/chrome/uCz7pqmA8b4

This may be a bug in iOS Chrome :-( :-( :-(

**Comment by rickpern** [comment]
yeah, i saw that too...i'm looking into it..just got distracted. i'll let you know what i find.

**Comment by rickpern** [comment]
I've confirmed that that example doesn't work in iOS Chrome. :(

**Comment by rickpern** [comment]
@mixonic i know you recently added localStorage to the mix, but do you think there is another possibility to maintain that state besides using localStorage?

**Comment by mixonic** [comment]
@rickpern Chrome and FF closed one avenue of passing data back and forth on us, so we needed to move to localStorage instead. If Chrome on iOS is broken we should open an issue upstream (with a repro) and I can try to get the Chrome team to pay attention.

**Comment by alisdair** [comment]
Confirming this is a problem for my app. Reported on Chromium tracker here: https://code.google.com/p/chromium/issues/detail?id=525262

**Comment by hhff** [comment]
Same here

![image](https://cloud.githubusercontent.com/assets/2865404/11230817/2502cb04-8dee-11e5-81d8-7c63239f9b0f.png)

**Comment by hhff** [comment]
Hi guys, got a Torii style workaround for this that I'll share when I get a chance to tidy up the code!

**Comment by hhff** [comment]
Hey all - here's my workaround using the Facebook Manual Login Flow: https://medium.com/@hhff/patching-torii-s-facebook-connect-for-chrome-ios-15011d49eade#.5ozbewwcf

**Comment by mitchlloyd** [comment]
According to this Chrome bug report this issue was recently fixed in version M48: https://code.google.com/p/chromium/issues/detail?id=525262

**Comment by wereldbolt** [comment]
Using my phone to check the solution I noticed that the bug in Chrome OS has gone (http://html5demos.com/storage-events) but in Torii the bug still exists.
