### ISSUE TITLE
Doesn't work with ember 2.13.0-beta.1

### ISSUE THREAD

**Issue by Padchi** [Vestorly/torii#349]
Just upgraded to `ember 2.13.0-beta.1` and torii can't find the torii service when trying to open a provider, getting `Cannot read property 'open' of undefined` at https://github.com/Vestorly/torii/blob/master/addon/services/torii-session.js#L43  which indicates that the torii service is undefined inside torii-session service.

```
// env
var ENV = {
  torii: { sessionServiceName: 'session' }
}

// controller
actions: {
  signIn(identification, password) {
    return get(this, 'session').open('oauth2-password-grant', { identification, password });
  }
}
```

EDIT..
Trying to debugg this and injecting the `torii` service in the `torii-session` service works. However `getOwner(this)` is always undefined so the open of a adapter always fails.

**Comment by mwpastore** [comment]
Experiencing the same issue here. I can run with ember-resolver 4.x and ember-cli-babel 6.x (beta) and everything else at the latest and greatest, but as soon as I bump ember-source to 2.13.x, it breaks with this error.

**Comment by Cryrivers** [comment]
got the same issue

**Comment by Dhaulagiri** [comment]
Does this still persist in the release version of 2.13? Our setup seems to work with it but I'm not sure if we are doing something different here.

**Comment by Cryrivers** [comment]
@Dhaulagiri I'm using 2.13.0 (Stable version) and my case is the same as #353. Now I've got to fall back to Ember 2.12.0.

**Comment by j-chaidez** [comment]
I was having the same problem with v2.13.0. I decided to go back two versions (2.11.0). The example inside of ember-simple-auth works now.

**Comment by vsymguysung** [comment]
I am having the same issue with `v2.13.0`too. From some debugging, I found that `this.get('torii')` inside `open` method always return `undefined` in the `addon/services/torii-session.js`.

**Comment by crodriguez1a** [comment]
@Dhaulagiri Heads up...2.13.0-beta.2 may create a regression. I was seeing`getOwner(this)` return undefined. May have to do something like:

```es6
    var owner     = getOwner(this) || this.container,
        torii     = owner.lookup('service:torii'),
        sm        = this.get('stateMachine');
```
Still not sure what the underlying cause really is.

**Comment by Dhaulagiri** [comment]
@crodriguez1a at this point you should be using the 2.13 release version (unless you are trying the 2.14 betas?)

**Comment by crodriguez1a** [comment]
@Dhaulagiri I opted in to a 2.13 beta for a minor bug-fix, but I reverted back. I'm hoping 2.14 will not inherit any of this stuff.

**Comment by Dhaulagiri** [comment]
@crodriguez1a i don't understand why you are using the beta at all at this point?

**Comment by crodriguez1a** [comment]
@Dhaulagiri  I meant to say 2.14 (as you pointed out). Sorry for the confusion.

**Comment by krisselden** [comment]
anyone have a reproduction or specific Safari versions/platforms?   has anyone who can reproduce seen this in WebKit nightly?

**Comment by jdurand** [comment]
@krisselden this issue was fixed in https://github.com/Vestorly/torii/pull/355

**Comment by trokelado** [comment]
I am having the same issue with  v2.14.2 with same error on line 49 of torii-session.
return adapter.open(authorization);
In my case solution #355 is implemented but error persist.
Any help will be appreciated cause I´m newbee and really need an auth.
